

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAMES ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAMES ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findhidapi.cmake")
# Global approach
set(hidapi_FOUND 1)
set(hidapi_VERSION "0.10.1")

find_package_handle_standard_args(hidapi REQUIRED_VARS
                                  hidapi_VERSION VERSION_VAR hidapi_VERSION)
mark_as_advanced(hidapi_FOUND hidapi_VERSION)


set(hidapi_INCLUDE_DIRS "C:/Users/anton/.conan/data/hidapi/0.10.1/_/_/package/127af201a4cdf8111e2e08540525c245c9b3b99e/include")
set(hidapi_INCLUDE_DIR "C:/Users/anton/.conan/data/hidapi/0.10.1/_/_/package/127af201a4cdf8111e2e08540525c245c9b3b99e/include")
set(hidapi_INCLUDES "C:/Users/anton/.conan/data/hidapi/0.10.1/_/_/package/127af201a4cdf8111e2e08540525c245c9b3b99e/include")
set(hidapi_RES_DIRS )
set(hidapi_DEFINITIONS )
set(hidapi_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(hidapi_COMPILE_DEFINITIONS )
set(hidapi_COMPILE_OPTIONS_LIST "" "")
set(hidapi_COMPILE_OPTIONS_C "")
set(hidapi_COMPILE_OPTIONS_CXX "")
set(hidapi_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(hidapi_LIBRARIES "") # Will be filled later
set(hidapi_LIBS "") # Same as hidapi_LIBRARIES
set(hidapi_SYSTEM_LIBS )
set(hidapi_FRAMEWORK_DIRS )
set(hidapi_FRAMEWORKS )
set(hidapi_FRAMEWORKS_FOUND "") # Will be filled later
set(hidapi_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(hidapi_FRAMEWORKS_FOUND "${hidapi_FRAMEWORKS}" "${hidapi_FRAMEWORK_DIRS}")

mark_as_advanced(hidapi_INCLUDE_DIRS
                 hidapi_INCLUDE_DIR
                 hidapi_INCLUDES
                 hidapi_DEFINITIONS
                 hidapi_LINKER_FLAGS_LIST
                 hidapi_COMPILE_DEFINITIONS
                 hidapi_COMPILE_OPTIONS_LIST
                 hidapi_LIBRARIES
                 hidapi_LIBS
                 hidapi_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to hidapi_LIBS and hidapi_LIBRARY_LIST
set(hidapi_LIBRARY_LIST hidapi)
set(hidapi_LIB_DIRS "C:/Users/anton/.conan/data/hidapi/0.10.1/_/_/package/127af201a4cdf8111e2e08540525c245c9b3b99e/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_hidapi_DEPENDENCIES "${hidapi_FRAMEWORKS_FOUND} ${hidapi_SYSTEM_LIBS} ")

conan_package_library_targets("${hidapi_LIBRARY_LIST}"  # libraries
                              "${hidapi_LIB_DIRS}"      # package_libdir
                              "${_hidapi_DEPENDENCIES}"  # deps
                              hidapi_LIBRARIES            # out_libraries
                              hidapi_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "hidapi")                                      # package_name

set(hidapi_LIBS ${hidapi_LIBRARIES})

foreach(_FRAMEWORK ${hidapi_FRAMEWORKS_FOUND})
    list(APPEND hidapi_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND hidapi_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${hidapi_SYSTEM_LIBS})
    list(APPEND hidapi_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND hidapi_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(hidapi_LIBRARIES_TARGETS "${hidapi_LIBRARIES_TARGETS};")
set(hidapi_LIBRARIES "${hidapi_LIBRARIES};")

set(CMAKE_MODULE_PATH "C:/Users/anton/.conan/data/hidapi/0.10.1/_/_/package/127af201a4cdf8111e2e08540525c245c9b3b99e/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/anton/.conan/data/hidapi/0.10.1/_/_/package/127af201a4cdf8111e2e08540525c245c9b3b99e/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET hidapi::hidapi)
        add_library(hidapi::hidapi INTERFACE IMPORTED)
        if(hidapi_INCLUDE_DIRS)
            set_target_properties(hidapi::hidapi PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${hidapi_INCLUDE_DIRS}")
        endif()
        set_property(TARGET hidapi::hidapi PROPERTY INTERFACE_LINK_LIBRARIES
                     "${hidapi_LIBRARIES_TARGETS};${hidapi_LINKER_FLAGS_LIST}")
        set_property(TARGET hidapi::hidapi PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${hidapi_COMPILE_DEFINITIONS})
        set_property(TARGET hidapi::hidapi PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${hidapi_COMPILE_OPTIONS_LIST}")
        
    endif()
endif()

foreach(_BUILD_MODULE_PATH ${hidapi_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
