#!/bin/sh

# Folders for XML configuration files
avm_debug_path=$HOME/.local/share/AVM-Debug
avm_service_path=$HOME/.local/share/AVM-Service

# Clean folder for AVM-Debug if it's exist
if [ -d "$avm_debug_path" ]; then
  echo "$avm_debug_path does exist, cleanup."
  rm -rf "$avm_debug_path"
  mkdir "$avm_debug_path"
fi

# Clean folder for AVM-Service if it's exist
if [ -d "$avm_service_path" ]; then
  echo "$avm_service_path does exist, cleanup."
  rm -rf "$avm_service_path"
  mkdir "$avm_service_path"
fi

# Copying XML configuration files in appdata folder
for xml_file in /usr/share/coma/settings/*.xml
do
    cp "$xml_file" "$avm_debug_path"
    cp "$xml_file" "$avm_service_path"
done

# Remove source folder
rm -rf /usr/share/coma
