# Recursively generate sources and headers for protobuf files

function(generate_protos FOLDER)
    file(GLOB_RECURSE proto_files CONFIGURE_DEPENDS  RELATIVE ${FOLDER} "*.proto" )
    message(STATUS "Proto files: " ${proto_files})
    foreach(PROTO_FILE IN LISTS proto_files)
      #message(STATUS "protoc proto(cc): ${PROTO_FILE}")
      get_filename_component(PROTO_DIR ${PROTO_FILE} DIRECTORY)
      get_filename_component(PROTO_NAME ${PROTO_FILE} NAME_WE)
      set(${PROTO_HDR} ${PROJECT_BINARY_DIR}/${PROTO_DIR}/${PROTO_NAME}.pb.h)
      set(${PROTO_SRC} ${PROJECT_BINARY_DIR}/${PROTO_DIR}/${PROTO_NAME}.pb.cc)
      #message(STATUS "protoc hdr: ${PROTO_HDR}")
      #message(STATUS "protoc src: ${PROTO_SRC}")
      protobuf_generate_cpp(PROTO_SRC PROTO_HDR protos/${PROTO_FILE})
      list(APPEND PROTO_HDRS ${PROTO_HDR})
      list(APPEND PROTO_SRCS ${PROTO_SRC})
      set(PROTO_SRCS ${PROTO_SRCS} PARENT_SCOPE)
      set(PROTO_HDRS ${PROTO_SRCS} PARENT_SCOPE)
    endforeach()
    message(STATUS "Generated srcs: " ${PROTO_SRCS})
    message(STATUS "Generated hdrs: " ${PROTO_HDRS})
endfunction()
