# Global cpack settings
set(CPACK_GENERATOR "DEB")
set(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)
set(CPACK_DEB_COMPONENT_INSTALL ON) # magic required for separate packaging components
set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS ON)
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_PACKAGE_CONTACT "info@avmenergo.ru") # TODO: change to support email?
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${SOFTDEVELOPER} <${CPACK_PACKAGE_CONTACT}>") #required
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

# Settings for AVM-Debug component
set(CPACK_DEBIAN_AVMDEBUG_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_AVMDEBUG_PACKAGE_NAME "avm-debug")
set(CPACK_DEBIAN_AVMDEBUG_DESCRIPTION  "АВМ-Наладка")
set(DEBUG_POSTINST "${CMAKE_CURRENT_BINARY_DIR}/AVM-Debug/postinst")
set(DEBUG_POSTRM   "${CMAKE_CURRENT_BINARY_DIR}/AVM-Debug/postrm"  )
set(CPACK_DEBIAN_AVMDEBUG_PACKAGE_CONTROL_EXTRA "${DEBUG_POSTINST}" "${DEBUG_POSTRM}")

# Settings for AVM-Service component
set(CPACK_DEBIAN_AVMSERVICE_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_AVMSERVICE_PACKAGE_NAME "avm-service")
set(CPACK_DEBIAN_AVMSERVICE_DESCRIPTION  "АВМ-Сервис")
set(SERVICE_POSTINST "${CMAKE_CURRENT_BINARY_DIR}/AVM-Service/postinst")
set(SERVICE_POSTRM   "${CMAKE_CURRENT_BINARY_DIR}/AVM-Service/postrm"  )
set(CPACK_DEBIAN_AVMSERVICE_PACKAGE_CONTROL_EXTRA "${SERVICE_POSTINST}" "${SERVICE_POSTRM}")

include(CPack)
