# Debug purposes
message(STATUS "Components to pack: ${CPACK_COMPONENTS_ALL}")
set(VERBOSE_LOGGING FALSE)

# Package settings
set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_PACKAGE_CONTACT "info@avmenergo.ru") # TODO: change to support email?
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${SOFTDEVELOPER} <${CPACK_PACKAGE_CONTACT}>") #required
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "COMplex for Avtuk")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/../license.txt")
set(CPACK_RESOURCE_FILE_README  "${CMAKE_CURRENT_SOURCE_DIR}/../README.md")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEB_COMPONENT_INSTALL ON) # magic required for separate packaging components

# Extra Debian package settings
set(POSTINST "${CMAKE_CURRENT_SOURCE_DIR}/../scripts/postinst")
set(POSTRM   "${CMAKE_CURRENT_SOURCE_DIR}/../scripts/postrm")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA  "${POSTINST};${POSTRM}")
set(CPACK_DEB_POST_INSTALL_SCRIPT_FILE   ${POSTINST})
set(CPACK_DEB_POST_UNINSTALL_SCRIPT_FILE ${POSTRM})
include(CPack)
